In [ ]:
# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Bring-Your-Own-Autorater using `CustomMetric`

<table align="left">
  <td style="text-align: center">
    <a href="https://colab.research.google.com/github/GoogleCloudPlatform/generative-ai/blob/main/gemini/evaluation/evaltask_approach/bring_your_own_autorater_with_custom_metric.ipynb">
      <img width="32px" src="https://www.gstatic.com/pantheon/images/bigquery/welcome_page/colab-logo.svg" alt="Google Colaboratory logo"><br> Open in Colab
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/colab/import/https:%2F%2Fraw.githubusercontent.com%2FGoogleCloudPlatform%2Fgenerative-ai%2Fmain%2Fgemini%2Fevaluation%2Fevaltask_approach%2Fbring_your_own_autorater_with_custom_metric.ipynb">
      <img width="32px" src="https://lh3.googleusercontent.com/JmcxdQi-qOpctIvWKgPtrzZdJJK-J3sWE1RsfjZNwshCFgE_9fULcNpuXYTilIR2hjwN" alt="Google Cloud Colab Enterprise logo"><br> Open in Colab Enterprise
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/workbench/deploy-notebook?download_url=https://raw.githubusercontent.com/GoogleCloudPlatform/generative-ai/main/gemini/evaluation/evaltask_approach/bring_your_own_autorater_with_custom_metric.ipynb">
      <img src="https://www.gstatic.com/images/branding/gcpiconscolors/vertexai/v1/32px.svg" alt="Vertex AI logo"><br> Open in Vertex AI Workbench
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://github.com/GoogleCloudPlatform/generative-ai/blob/main/gemini/evaluation/evaltask_approach/bring_your_own_autorater_with_custom_metric.ipynb">
      <img width="32px" src="https://raw.githubusercontent.com/primer/octicons/refs/heads/main/icons/mark-github-24.svg" alt="GitHub logo"><br> View on GitHub
    </a>
  </td>
</table>

<div style="clear: both;"></div>

<b>Share to:</b>

<a href="https://www.linkedin.com/sharing/share-offsite/?url=https%3A//github.com/GoogleCloudPlatform/generative-ai/blob/main/gemini/evaluation/evaltask_approach/bring_your_own_autorater_with_custom_metric.ipynb" target="_blank">
  <img width="20px" src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="LinkedIn logo">
</a>

<a href="https://bsky.app/intent/compose?text=https%3A//github.com/GoogleCloudPlatform/generative-ai/blob/main/gemini/evaluation/evaltask_approach/bring_your_own_autorater_with_custom_metric.ipynb" target="_blank">
  <img width="20px" src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="Bluesky logo">
</a>

<a href="https://twitter.com/intent/tweet?url=https%3A//github.com/GoogleCloudPlatform/generative-ai/blob/main/gemini/evaluation/evaltask_approach/bring_your_own_autorater_with_custom_metric.ipynb" target="_blank">
  <img width="20px" src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X logo">
</a>

<a href="https://reddit.com/submit?url=https%3A//github.com/GoogleCloudPlatform/generative-ai/blob/main/gemini/evaluation/evaltask_approach/bring_your_own_autorater_with_custom_metric.ipynb" target="_blank">
  <img width="20px" src="https://redditinc.com/hubfs/Reddit%20Inc/Brand/Reddit_Logo.png" alt="Reddit logo">
</a>

<a href="https://www.facebook.com/sharer/sharer.php?u=https%3A//github.com/GoogleCloudPlatform/generative-ai/blob/main/gemini/evaluation/evaltask_approach/bring_your_own_autorater_with_custom_metric.ipynb" target="_blank">
  <img width="20px" src="https://upload.wikimedia.org/wikipedia/commons/5/51/Facebook_f_logo_%282019%29.svg" alt="Facebook logo">
</a>

| | |
|-|-|
|Author(s) | [Jason Dai](https://github.com/jsondai) |

## Overview

Use the *Vertex AI Python SDK for Gen AI Evaluation Service* to evaluate generative AI models with your locally-defined `CustomMetric`, and use your own autorater model to perform model-based metric evaluation.

## Getting Started

### Install Vertex AI Python SDK for Gen AI Evaluation Service

In [ ]:
%pip install --upgrade --user --quiet google-cloud-aiplatform[evaluation] google-genai

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python3 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.
  DEPRECATION: Building 'google-cloud-aiplatform' using the legacy setup.py bdist_wheel mechanism, which will be removed in a future version. pip 25.3 will enforce this behaviour change. A possible replacement is to use the standardized build interface by setting the `--use-pep517` option, (possibly combined with `--no-build-isolation`), or adding a `pyproject.toml` file to the source tree of 'google-cloud-aiplatform'. Discussion can be found at https://github.com/pypa/pip/issues/6334
  WARNING: The script websockets is installed in '/Library/Frameworks/Python.framework/Versions/3.13/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script distro is installed in '/Library/Frameworks/Python.framework/Versions/3.13/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script normalizer is installed in '/Library/Frameworks/Python.framework/Versions/3.13/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script httpx is installed in '/Library/Frameworks/Python.framework/Versions/3.13/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script tb-gcp-uploader is installed in '/Library/Frameworks/Python.framework/Versions/3.13/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python3 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

### Restart runtime
To use the newly installed packages in this Jupyter runtime, you must restart the runtime. You can do this by running the cell below, which restarts the current kernel.

The restart might take a minute or longer. After it's restarted, continue to the next step.

In [ ]:
import IPython

app = IPython.Application.instance()
app.kernel.do_shutdown(True)

{'status': 'ok', 'restart': True}

:

<div class="alert alert-block alert-warning">
<b>⚠️ The kernel is going to restart. Wait until it's finished before continuing to the next step. ⚠️</b>
</div>

### Authenticate your notebook environment (Colab only)

In [2]:
import sys

if "google.colab" in sys.modules:
    from google.colab import auth

    auth.authenticate_user()

### Set Google Cloud project information and initialize Vertex AI SDK"

In [3]:
PROJECT_ID = "model-evaluation-dev"  # @param {type:"string"}
LOCATION = "us-central1"  # @param {type:"string"}

if not PROJECT_ID or PROJECT_ID == "[your-project-id]":
    raise ValueError("Please set your PROJECT_ID")


import vertexai

vertexai.init(project=PROJECT_ID, location=LOCATION)

### Import libraries

In [4]:
import inspect
import json

import pandas as pd
from google import genai
from google.genai import types
from vertexai.evaluation import CustomMetric, EvalTask
from vertexai.preview.evaluation import notebook_utils

## Using locally-defined `CustomMetric` class

### Documentation

In [5]:
print(f"{CustomMetric.__name__}:\n{inspect.getdoc(CustomMetric)}\n")

CustomMetric:
The custom evaluation metric.

A fully-customized CustomMetric that can be used to evaluate a single model
by defining a metric function for a computation-based metric. The
CustomMetric is computed on the client-side using the user-defined metric
function in SDK only, not by the Vertex Gen AI Evaluation Service.

  Attributes:
    name: The name of the metric.
    metric_function: The user-defined evaluation function to compute a metric
      score. Must use the dataset row dictionary as the metric function
      input and return per-instance metric result as a dictionary output.
      The metric score must mapped to the name of the CustomMetric as key.

### Define a `CustomMetric` and "Bring-Your-Own-Autorater"

Define a custom model-based metric and "Bring-Your-Own-Autorater". The custom model-based metric can contain multiple fields such as an autorater-graded score, explanations for the score, and more. The score field must match the name of the metric, other fields can be freeform strings.

In [6]:
# Bring-Your-Own-Autorater and define your autorater inference function


def get_autorater_response(metric_prompt: str) -> dict:
    client = genai.Client(vertexai=True, project=PROJECT_ID, location=LOCATION)

    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=metric_prompt,
        config=types.GenerateContentConfig(
            response_mime_type="application/json",
            response_schema={
                "type": "OBJECT",
                "properties": {
                    "score": {"type": "NUMBER"},
                    "explanation": {"type": "STRING"},
                },
                "required": ["score", "explanation"],
            },
            safety_settings=[
                types.SafetySetting(
                    category="HARM_CATEGORY_HATE_SPEECH",
                    threshold="BLOCK_NONE",
                ),
                types.SafetySetting(
                    category="HARM_CATEGORY_DANGEROUS_CONTENT",
                    threshold="BLOCK_NONE",
                ),
                types.SafetySetting(
                    category="HARM_CATEGORY_SEXUALLY_EXPLICIT",
                    threshold="BLOCK_NONE",
                ),
                types.SafetySetting(
                    category="HARM_CATEGORY_HARASSMENT",
                    threshold="BLOCK_NONE",
                ),
            ],
        ),
    )

    return response.parsed

In [7]:
# Define your metric computation function


def linguistic_acceptability_fn(instance: dict) -> dict:
    metric_prompt_template = """
# Instruction
You are an expert evaluator. Your task is to evaluate the quality of the responses generated by AI models. We will provide you with the user prompt and an AI-generated responses.
You should first read the user input carefully for analyzing the task, and then evaluate the quality of the responses based on the Criteria provided in the Evaluation section below.
You will assign the response a rating following the Rating Rubric and Evaluation Steps. Give step by step explanations for your rating, and only choose ratings from the Rating Rubric.


# Evaluation
## Criteria
Appropriate word choice: Words chosen are appropriate and purposeful given their relative context and positioning in the text. Vocabulary demonstrates prompt understanding.
Proper Grammar: The language's grammar rules are correctly followed, including but not limited to sentence structures, verb tenses, subject-verb agreement, proper punctuation, and capitalization.
Reference Alignment: The response is consistent and aligned with the reference.

## Rating Rubric
1: Poor: The writing is riddled with grammatical errors, uses highly inappropriate vocabulary, is completely unrelated to the reference.
2: Unsatisfactory: The writing has significant grammatical errors, uses inappropriate vocabulary, deviates significantly from the reference.
3: Satisfactory: The writing may have minor grammatical errors or use less-appropriate vocabulary, but it aligns reasonably well with the reference.
4: Good: The writing is generally grammatically correct, uses appropriate vocabulary and aligns well with the reference.
5: Excellent: The writing is grammatically correct, uses appropriate vocabulary and aligns perfectly with the reference.

## Evaluation Steps
Step 1: Assess the response in aspects of all criteria provided. Provide assessment according to each criterion.
Step 2: Score based on the rating rubric. Give a brief rationale to explain your evaluation considering each individual criterion.


# User Inputs and AI-generated Response
## User Inputs
### prompt
{prompt}

## AI-generated Response
{response}
"""
    prompt = instance["prompt"]
    response = instance["response"]

    metric_prompt = metric_prompt_template.format(prompt=prompt, response=response)

    response_dict = get_autorater_response(metric_prompt)

    return {
        "linguistic_acceptability": response_dict["score"],
        "explanation": response_dict["explanation"],
    }

In [8]:
# Define a CustomMetric
linguistic_acceptability_metric = CustomMetric(
    name="linguistic_acceptability",
    metric_function=linguistic_acceptability_fn,
)

### Run Evaluations with `CustomMetric`

* The registered custom metrics are computed on the client side, without using Vertex Gen AI Evaluation Service APIs.

* Mixing CustomMetric instances and other types of metrics is supported.

* You can handle rate limiting of your own autorater with Eval SDK's [RateLimiter utils function](https://github.com/googleapis/python-aiplatform/blob/20f2cad85719b4793c2b77bf36c5a0d775b1a825/vertexai/evaluation/utils.py#L104) based on your autorater's capacity and QPS limit.

#### Define an evaluation dataset

In [9]:
instruction = "Summarize the following article"

context = [
    "To make a classic spaghetti carbonara, start by bringing a large pot of salted water to a boil. While the water is heating up, cook pancetta or guanciale in a skillet with olive oil over medium heat until it's crispy and golden brown. Once the pancetta is done, remove it from the skillet and set it aside. In the same skillet, whisk together eggs, grated Parmesan cheese, and black pepper to make the sauce. When the pasta is cooked al dente, drain it and immediately toss it in the skillet with the egg mixture, adding a splash of the pasta cooking water to create a creamy sauce.",
    "Preparing a perfect risotto requires patience and attention to detail. Begin by heating butter in a large, heavy-bottomed pot over medium heat. Add finely chopped onions and minced garlic to the pot, and cook until they're soft and translucent, about 5 minutes. Next, add Arborio rice to the pot and cook, stirring constantly, until the grains are coated with the butter and begin to toast slightly. Pour in a splash of white wine and cook until it's absorbed. From there, gradually add hot chicken or vegetable broth to the rice, stirring frequently, until the risotto is creamy and the rice is tender with a slight bite.",
    "For a flavorful grilled steak, start by choosing a well-marbled cut of beef like ribeye or New York strip. Season the steak generously with kosher salt and freshly ground black pepper on both sides, pressing the seasoning into the meat. Preheat a grill to high heat and brush the grates with oil to prevent sticking. Place the seasoned steak on the grill and cook for about 4-5 minutes on each side for medium-rare, or adjust the cooking time to your desired level of doneness. Let the steak rest for a few minutes before slicing against the grain and serving.",
    "Creating a creamy homemade tomato soup is a comforting and simple process. Begin by heating olive oil in a large pot over medium heat. Add diced onions and minced garlic to the pot and cook until they're soft and fragrant. Next, add chopped fresh tomatoes, chicken or vegetable broth, and a sprig of fresh basil to the pot. Simmer the soup for about 20-30 minutes, or until the tomatoes are tender and falling apart. Remove the basil sprig and use an immersion blender to puree the soup until smooth. Season with salt and pepper to taste before serving.",
    "To bake a decadent chocolate cake from scratch, start by preheating your oven to 350°F (175°C) and greasing and flouring two 9-inch round cake pans. In a large mixing bowl, cream together softened butter and granulated sugar until light and fluffy. Beat in eggs one at a time, making sure each egg is fully incorporated before adding the next. In a separate bowl, sift together all-purpose flour, cocoa powder, baking powder, baking soda, and salt. Divide the batter evenly between the prepared cake pans and bake for 25-30 minutes, or until a toothpick inserted into the center comes out clean.",
]

reference = [
    "The process of making spaghetti carbonara involves boiling pasta, crisping pancetta or guanciale, whisking together eggs and Parmesan cheese, and tossing everything together to create a creamy sauce.",
    "Preparing risotto entails sautéing onions and garlic, toasting Arborio rice, adding wine and broth gradually, and stirring until creamy and tender.",
    "Grilling a flavorful steak involves seasoning generously, preheating the grill, cooking to desired doneness, and letting it rest before slicing.",
    "Creating homemade tomato soup includes sautéing onions and garlic, simmering with tomatoes and broth, pureeing until smooth, and seasoning to taste.",
    "Baking a decadent chocolate cake requires creaming butter and sugar, beating in eggs and alternating dry ingredients with buttermilk before baking until done.",
]


eval_dataset = pd.DataFrame(
    {
        "context": context,
        "instruction": [instruction] * len(context),
        "reference": reference,
    }
)

#### Define prompt templates to compare

In [10]:
prompt_templates = [
    "Instruction: {instruction}. Article: {context}. Summary:",
    "Article: {context}. Complete this task: {instruction}, in three sentence. Summary:",
    "Goal: {instruction} and give me a TLDR. Here's a news article: {context}. Summary:",
]

#### Define metrics

In [11]:
metrics = ["rouge_l_sum", "fluency", "coherence", linguistic_acceptability_metric]

#### Define an EvalTask

In [12]:
experiment_name = "eval-custom-metric"  # @param {type:"string"}

eval_task = EvalTask(
    dataset=eval_dataset,
    metrics=metrics,
    experiment=experiment_name,
)

#### Run an Evaluation

In [13]:
eval_results = []

for i, prompt_template in enumerate(prompt_templates):
    eval_result = eval_task.evaluate(
        model="gemini-2.5-flash",
        prompt_template=prompt_template,
    )

    eval_results.append((f"Prompt #{i}", eval_result))

Associating projects/977012026409/locations/us-central1/metadataStores/default/contexts/eval-custom-metric-7d2bd761-c87a-4c9b-b63d-7af376525a7c to Experiment: eval-custom-metric

Logging Eval Experiment metadata: {'prompt_template': 'Instruction: {instruction}. Article: {context}. Summary:', 'model_name': 'gemini-2.5-flash'}
Assembling prompts from the `prompt_template`. The `prompt` column in the `EvalResult.metrics_table` has the assembled prompts used for model response generation.
Generating a total of 5 responses from Gemini model gemini-2.5-flash using genai module.

100%|██████████| 5/5 [00:04<00:00,  1.00it/s]

All 5 responses are successfully generated from Gemini model gemini-2.5-flash using genai module.
Multithreaded Batch Inference took: 5.050281833013287 seconds.
Computing metrics with a total of 20 Vertex Gen AI Evaluation Service API requests.

  5%|▌         | 1/20 [00:03<01:00,  3.20s/it]I0331 15:52:51.425703 2742393 fork_posix.cc:71] Other threads are currently calling into gRPC, skipping fork() handlers
 15%|█▌        | 3/20 [00:06<00:36,  2.16s/it]I0331 15:52:54.751088 2742570 fork_posix.cc:71] Other threads are currently calling into gRPC, skipping fork() handlers
I0331 15:52:54.757410 2742590 ev_poll_posix.cc:593] FD from fork parent still in poll list: fd(97, generation: 1)
 45%|████▌     | 9/20 [00:13<00:18,  1.68s/it]I0331 15:53:04.997234 2742568 fork_posix.cc:71] Other threads are currently calling into gRPC, skipping fork() handlers
I0331 15:53:05.013000 2742788 ev_poll_posix.cc:593] FD from fork parent still in poll list: fd(97, generation: 1)
 65%|██████▌   | 13/20 [00:22<00:12,  1.78s/it]I0331 15:53:10.374939 2742486 fork_posix.cc:71] Other threads are currently calling into gRPC, skipping fork() handlers
I0331 15:53:10.381579 2742936 ev_poll_posix.cc:593] FD from fork parent still in poll list: fd(97, generation: 1)
100%|██████████| 20/20 [00:29<00:00,  1.46s/it]

All 20 metric requests are successfully computed.
Evaluation Took:29.22343687497778 seconds

Associating projects/977012026409/locations/us-central1/metadataStores/default/contexts/eval-custom-metric-6163bf83-0c29-4d1f-b18f-d811c120342b to Experiment: eval-custom-metric

Logging Eval Experiment metadata: {'prompt_template': 'Article: {context}. Complete this task: {instruction}, in three sentence. Summary:', 'model_name': 'gemini-2.5-flash'}
Assembling prompts from the `prompt_template`. The `prompt` column in the `EvalResult.metrics_table` has the assembled prompts used for model response generation.
Generating a total of 5 responses from Gemini model gemini-2.5-flash using genai module.

100%|██████████| 5/5 [00:02<00:00,  2.21it/s]

All 5 responses are successfully generated from Gemini model gemini-2.5-flash using genai module.
Multithreaded Batch Inference took: 2.3081210420059506 seconds.
Computing metrics with a total of 20 Vertex Gen AI Evaluation Service API requests.

  5%|▌         | 1/20 [00:05<01:51,  5.89s/it]I0331 15:53:29.544988 2743427 fork_posix.cc:71] Other threads are currently calling into gRPC, skipping fork() handlers
 15%|█▌        | 3/20 [00:10<00:54,  3.21s/it]I0331 15:53:33.875705 2743551 fork_posix.cc:71] Other threads are currently calling into gRPC, skipping fork() handlers
I0331 15:53:33.881471 2743571 ev_poll_posix.cc:593] FD from fork parent still in poll list: fd(97, generation: 1)
 35%|███▌      | 7/20 [00:15<00:29,  2.27s/it]I0331 15:53:39.609990 2743426 fork_posix.cc:71] Other threads are currently calling into gRPC, skipping fork() handlers
I0331 15:53:39.615730 2743693 ev_poll_posix.cc:593] FD from fork parent still in poll list: fd(97, generation: 1)
 65%|██████▌   | 13/20 [00:21<00:06,  1.05it/s]I0331 15:53:44.877273 2743268 fork_posix.cc:71] Other threads are currently calling into gRPC, skipping fork() handlers
I0331 15:53:44.882840 2743819 ev_poll_posix.cc:593] FD from fork parent still in poll list: fd(97, generation: 1)
100%|██████████| 20/20 [00:32<00:00,  1.62s/it]

All 20 metric requests are successfully computed.
Evaluation Took:32.38341779098846 seconds

Associating projects/977012026409/locations/us-central1/metadataStores/default/contexts/eval-custom-metric-8332bb3d-edd8-4b6f-a9e7-dc0721ae922c to Experiment: eval-custom-metric

Logging Eval Experiment metadata: {'prompt_template': "Goal: {instruction} and give me a TLDR. Here's a news article: {context}. Summary:", 'model_name': 'gemini-2.5-flash'}
Assembling prompts from the `prompt_template`. The `prompt` column in the `EvalResult.metrics_table` has the assembled prompts used for model response generation.
Generating a total of 5 responses from Gemini model gemini-2.5-flash using genai module.

100%|██████████| 5/5 [00:07<00:00,  1.44s/it]

All 5 responses are successfully generated from Gemini model gemini-2.5-flash using genai module.
Multithreaded Batch Inference took: 7.257108165998943 seconds.
Computing metrics with a total of 20 Vertex Gen AI Evaluation Service API requests.

  5%|▌         | 1/20 [00:05<01:49,  5.74s/it]I0331 15:54:12.934641 2744290 fork_posix.cc:71] Other threads are currently calling into gRPC, skipping fork() handlers
 25%|██▌       | 5/20 [00:11<00:23,  1.55s/it]I0331 15:54:18.245668 2744496 fork_posix.cc:71] Other threads are currently calling into gRPC, skipping fork() handlers
I0331 15:54:18.251510 2744517 ev_poll_posix.cc:593] FD from fork parent still in poll list: fd(91, generation: 1)
 40%|████      | 8/20 [00:15<00:17,  1.45s/it]I0331 15:54:22.401842 2744609 fork_posix.cc:71] Other threads are currently calling into gRPC, skipping fork() handlers
I0331 15:54:22.407522 2744634 ev_poll_posix.cc:593] FD from fork parent still in poll list: fd(91, generation: 1)
 60%|██████    | 12/20 [00:20<00:11,  1.39s/it]I0331 15:54:27.299682 2744398 fork_posix.cc:71] Other threads are currently calling into gRPC, skipping fork() handlers
I0331 15:54:27.305722 2744756 ev_poll_posix.cc:593] FD from fork parent still in poll list: fd(91, generation: 1)
100%|██████████| 20/20 [00:29<00:00,  1.48s/it]

All 20 metric requests are successfully computed.
Evaluation Took:29.608971624984406 seconds

#### Display Evaluation result and explanations

In [14]:
for title, eval_result in eval_results:
    notebook_utils.display_eval_result(title=title, eval_result=eval_result)

## Prompt #0

### Summary Metrics

,row_count,rouge_l_sum/mean,rouge_l_sum/std,fluency/mean,fluency/std,coherence/mean,coherence/std,linguistic_acceptability/mean,linguistic_acceptability/std
0,5.0,0.31619,0.08563,5.0,0.0,5.0,0.0,5.0,0.0

### Row-based Metrics

,context,instruction,reference,prompt,response,linguistic_acceptability/score,linguistic_acceptability/explanation,rouge_l_sum/score,fluency/explanation,fluency/score,coherence/explanation,coherence/score
0,"To make a classic spaghetti carbonara, start b...",Summarize the following article,The process of making spaghetti carbonara invo...,Instruction: Summarize the following article. ...,"To make classic spaghetti carbonara, first boi...",5,The response demonstrates excellent quality ac...,0.280000,"The response is free of grammatical errors, de...",5.0,The summary demonstrates seamless logical flow...,5.0
1,Preparing a perfect risotto requires patience ...,Summarize the following article,Preparing risotto entails sautéing onions and ...,Instruction: Summarize the following article. ...,"To prepare risotto, begin by sautéing onions a...",5,Step 1: Assess the response in aspects of all ...,0.468750,"The response is grammatically perfect, uses pr...",5.0,The summary demonstrates exceptional logical f...,5.0
2,"For a flavorful grilled steak, start by choosi...",Summarize the following article,Grilling a flavorful steak involves seasoning ...,Instruction: Summarize the following article. ...,"To grill a flavorful steak, select a well-marb...",5,The AI-generated response provides an excellen...,0.275000,"The response is free of grammatical errors, us...",5.0,The summary demonstrates a seamless logical fl...,5.0
3,Creating a creamy homemade tomato soup is a co...,Summarize the following article,Creating homemade tomato soup includes sautéin...,Instruction: Summarize the following article. ...,"To make a creamy homemade tomato soup, heat ol...",5,Step 1: Assess the response in aspects of all ...,0.289157,"The response is free of grammatical errors, de...",5.0,The AI-generated response provides a completel...,5.0
4,To bake a decadent chocolate cake from scratch...,Summarize the following article,Baking a decadent chocolate cake requires crea...,Instruction: Summarize the following article. ...,"To bake a decadent chocolate cake, preheat the...",5,The AI-generated response provides an excellen...,0.268041,"The response is free of grammatical errors, de...",5.0,"The summary maintains a seamless logical flow,...",5.0

## Prompt #1

### Summary Metrics

,row_count,rouge_l_sum/mean,rouge_l_sum/std,fluency/mean,fluency/std,coherence/mean,coherence/std,linguistic_acceptability/mean,linguistic_acceptability/std
0,5.0,0.339235,0.075905,5.0,0.0,5.0,0.0,5.0,0.0

### Row-based Metrics

,context,instruction,reference,prompt,response,linguistic_acceptability/score,linguistic_acceptability/explanation,rouge_l_sum/score,fluency/explanation,fluency/score,coherence/explanation,coherence/score
0,"To make a classic spaghetti carbonara, start b...",Summarize the following article,The process of making spaghetti carbonara invo...,Article: To make a classic spaghetti carbonara...,"To make classic spaghetti carbonara, begin by ...",5,Step 1: Assess the response in aspects of all ...,0.391304,"The response is completely fluent, free of gra...",5.0,The response demonstrates a seamless logical f...,5.0
1,Preparing a perfect risotto requires patience ...,Summarize the following article,Preparing risotto entails sautéing onions and ...,Article: Preparing a perfect risotto requires ...,Preparing risotto involves first sautéing fine...,5,Step 1: Assess the response in aspects of all ...,0.419753,"The response is free of grammatical errors, de...",5.0,"The response is completely coherent, following...",5.0
2,"For a flavorful grilled steak, start by choosi...",Summarize the following article,Grilling a flavorful steak involves seasoning ...,"Article: For a flavorful grilled steak, start ...","Summary: To grill a flavorful steak, begin by ...",5,Step 1: Assess the response in aspects of all ...,0.282353,"The response is completely fluent, free of gra...",5.0,The AI-generated summary demonstrates exceptio...,5.0
3,Creating a creamy homemade tomato soup is a co...,Summarize the following article,Creating homemade tomato soup includes sautéin...,Article: Creating a creamy homemade tomato sou...,"Summary: To make creamy homemade tomato soup, ...",5,Step 1:\n* **Appropriate word choice**: The ...,0.363636,"The response is completely fluent, free of gra...",5.0,The AI-generated summary exhibits exceptional ...,5.0
4,To bake a decadent chocolate cake from scratch...,Summarize the following article,Baking a decadent chocolate cake requires crea...,Article: To bake a decadent chocolate cake fro...,"To bake a decadent chocolate cake, begin by pr...",5,Step 1: Assess the response in aspects of all ...,0.239130,"The response is free of grammatical errors, de...",5.0,"The response exhibits a seamless logical flow,...",5.0

## Prompt #2

### Summary Metrics

,row_count,rouge_l_sum/mean,rouge_l_sum/std,fluency/mean,fluency/std,coherence/mean,coherence/std,linguistic_acceptability/mean,linguistic_acceptability/std
0,5.0,0.238784,0.059885,5.0,0.0,5.0,0.0,5.0,0.0

### Row-based Metrics

,context,instruction,reference,prompt,response,linguistic_acceptability/score,linguistic_acceptability/explanation,rouge_l_sum/score,fluency/explanation,fluency/score,coherence/explanation,coherence/score
0,"To make a classic spaghetti carbonara, start b...",Summarize the following article,The process of making spaghetti carbonara invo...,Goal: Summarize the following article and give...,Here's the summary and TLDR for the article:\n...,5,Step 1: Assess the response in aspects of all ...,0.228571,"The response is free of grammatical errors, de...",5.0,The response provides a summary and TLDR that ...,5.0
1,Preparing a perfect risotto requires patience ...,Summarize the following article,Preparing risotto entails sautéing onions and ...,Goal: Summarize the following article and give...,**Summary:**\nPreparing perfect risotto requir...,5,The AI-generated response is excellent in all ...,0.322034,"The response is free of grammatical errors, de...",5.0,The response demonstrates excellent coherence ...,5.0
2,"For a flavorful grilled steak, start by choosi...",Summarize the following article,Grilling a flavorful steak involves seasoning ...,Goal: Summarize the following article and give...,"**Summary:**\nTo grill a flavorful steak, star...",5,Step 1: Assess the response in aspects of all ...,0.175182,The response is completely free of grammatical...,5.0,The response demonstrates excellent coherence ...,5.0
3,Creating a creamy homemade tomato soup is a co...,Summarize the following article,Creating homemade tomato soup includes sautéin...,Goal: Summarize the following article and give...,**Summary:**\nThis article outlines a simple r...,5,Step 1: Assess the response in aspects of all ...,0.274194,The response is completely fluent. It is free ...,5.0,The response demonstrates excellent coherence....,5.0
4,To bake a decadent chocolate cake from scratch...,Summarize the following article,Baking a decadent chocolate cake requires crea...,Goal: Summarize the following article and give...,**Summary:**\nThe article provides a step-by-s...,5,Step 1: Assess the response in aspects of all ...,0.193939,"The response is free of grammatical errors, de...",5.0,The AI-generated response demonstrates excepti...,5.0

In [15]:
for title, eval_result in eval_results:
    notebook_utils.display_explanations(
        eval_result, metrics=["linguistic_acceptability"]
    )

#### Compare Eval Results

In [16]:
notebook_utils.display_radar_plot(
    eval_results,
    metrics=["fluency", "coherence", "linguistic_acceptability"],
)

ImportError: `plotly` is not installed. Please install using "!pip install plotly"

In [ ]:
notebook_utils.display_bar_plot(eval_results, metrics=["rouge_l_sum"])

In [ ]:
eval_task.display_runs()