In [ ]:
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Analyzing movie posters in BigQuery with Gemini

<table align="left">
  <td style="text-align: center">
    <a href="https://colab.research.google.com/github/GoogleCloudPlatform/generative-ai/blob/main/gemini/use-cases/applying-llms-to-data/analyze-poster-images-in-bigquery/poster_image_analysis.ipynb">
      <img width="32px" src="https://www.gstatic.com/pantheon/images/bigquery/welcome_page/colab-logo.svg" alt="Google Colaboratory logo"><br> Open in Colab
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/colab/import/https:%2F%2Fraw.githubusercontent.com%2FGoogleCloudPlatform%2Fgenerative-ai%2Fmain%2Fgemini%2Fuse-cases%2Fapplying-llms-to-data%2Fanalyze-poster-images-in-bigquery%2Fposter_image_analysis.ipynb">
      <img width="32px" src="https://lh3.googleusercontent.com/JmcxdQi-qOpctIvWKgPtrzZdJJK-J3sWE1RsfjZNwshCFgE_9fULcNpuXYTilIR2hjwN" alt="Google Cloud Colab Enterprise logo"><br> Open in Colab Enterprise
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/workbench/deploy-notebook?download_url=https://raw.githubusercontent.com/GoogleCloudPlatform/generative-ai/main/gemini/use-cases/applying-llms-to-data/analyze-poster-images-in-bigquery/poster_image_analysis.ipynb">
      <img src="https://www.gstatic.com/images/branding/gcpiconscolors/vertexai/v1/32px.svg" alt="Vertex AI logo"><br> Open in Vertex AI Workbench
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/bigquery/import?url=https://github.com/GoogleCloudPlatform/generative-ai/blob/main/gemini/use-cases/applying-llms-to-data/analyze-poster-images-in-bigquery/poster_image_analysis.ipynb">
      <img src="https://www.gstatic.com/images/branding/gcpiconscolors/bigquery/v1/32px.svg" alt="BigQuery Studio logo"><br> Open in BigQuery Studio
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://github.com/GoogleCloudPlatform/generative-ai/blob/main/gemini/use-cases/applying-llms-to-data/analyze-poster-images-in-bigquery/poster_image_analysis.ipynb">
      <img width="32px" src="https://raw.githubusercontent.com/primer/octicons/refs/heads/main/icons/mark-github-24.svg" alt="GitHub logo"><br> View on GitHub
    </a>
  </td>
</table>

<div style="clear: both;"></div>

<b>Share to:</b>

<a href="https://www.linkedin.com/sharing/share-offsite/?url=https%3A//github.com/GoogleCloudPlatform/generative-ai/blob/main/gemini/use-cases/applying-llms-to-data/analyze-poster-images-in-bigquery/poster_image_analysis.ipynb" target="_blank">
  <img width="20px" src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="LinkedIn logo">
</a>

<a href="https://bsky.app/intent/compose?text=https%3A//github.com/GoogleCloudPlatform/generative-ai/blob/main/gemini/use-cases/applying-llms-to-data/analyze-poster-images-in-bigquery/poster_image_analysis.ipynb" target="_blank">
  <img width="20px" src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="Bluesky logo">
</a>

<a href="https://twitter.com/intent/tweet?url=https%3A//github.com/GoogleCloudPlatform/generative-ai/blob/main/gemini/use-cases/applying-llms-to-data/analyze-poster-images-in-bigquery/poster_image_analysis.ipynb" target="_blank">
  <img width="20px" src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X logo">
</a>

<a href="https://reddit.com/submit?url=https%3A//github.com/GoogleCloudPlatform/generative-ai/blob/main/gemini/use-cases/applying-llms-to-data/analyze-poster-images-in-bigquery/poster_image_analysis.ipynb" target="_blank">
  <img width="20px" src="https://redditinc.com/hubfs/Reddit%20Inc/Brand/Reddit_Logo.png" alt="Reddit logo">
</a>

<a href="https://www.facebook.com/sharer/sharer.php?u=https%3A//github.com/GoogleCloudPlatform/generative-ai/blob/main/gemini/use-cases/applying-llms-to-data/analyze-poster-images-in-bigquery/poster_image_analysis.ipynb" target="_blank">
  <img width="20px" src="https://upload.wikimedia.org/wikipedia/commons/5/51/Facebook_f_logo_%282019%29.svg" alt="Facebook logo">
</a>

| Author |
| --- |
| [Alicia Williams](https://github.com/aliciawilliams) |

## Overview

The objective is to demonstrate how to use the Gemini models for analysis in BigQuery, including:


*   Completing setup steps for accessing Vertex AI (including Gemini models) from BigQuery
*   Creating an Object Table for the unstructured dataset being analyzed
*   Performing analysis over the object table using the Gemini model
*   Joining analysis results back to structured table for deeper insights

## About the dataset

The dataset of movie poster images used in this demo are stored in a public Google Cloud Storage bucket: [`gs://cloud-samples-data/vertex-ai/dataset-management/datasets/classic-movie-posters`](https://console.cloud.google.com/storage/browser/cloud-samples-data/vertex-ai/dataset-management/datasets/classic-movie-posters)

![Movie Posters](https://storage.googleapis.com/github-repo/generative-ai/gemini/use-cases/applying-llms-to-data/movie-posters.jpeg)

## Services and Costs

This tutorial uses the following Google Cloud data analytics and ML services, they are billable components of Google Cloud:

* BigQuery & BigQuery ML [(pricing)](https://cloud.google.com/bigquery/pricing)
* Vertex AI API [(pricing)](https://cloud.google.com/vertex-ai/pricing)

Use the [Pricing Calculator](https://cloud.google.com/products/calculator/) to generate a cost estimate based on your projected usage.

# Setup steps for accessing Vertex AI models from BigQuery

https://docs.cloud.google.com/bigquery/docs/permissions-for-ai-functions#required_roles

To get the permissions that you need to run a query job that calls a Vertex AI model, ask your administrator to grant you the following IAM roles on the project:

Run query jobs: BigQuery Job User (roles/bigquery.jobUser)
Access a foundation model in Vertex AI: Vertex AI User (roles/aiplatform.user)

## Enable the Vertex AI and BigQuery Connection APIs

In [1]:
!gcloud services enable aiplatform.googleapis.com bigqueryconnection.googleapis.com

Operation "operations/acat.p2-735508242970-94f361ec-3e36-41d3-9e34-6752bed861c0" finished successfully.

# Create an object table for the movie poster images

## Create a new dataset named `'gemini_demo'`

In [5]:
%%bigquery
CREATE SCHEMA
  `gemini_demo` OPTIONS (location = 'US');

Query is running:   0%|          |

Empty DataFrame
Columns: []
Index: []

## Create an object table referencing Google Cloud Storage bucket

In [6]:
%%bigquery
CREATE OR REPLACE EXTERNAL TABLE
  `gemini_demo.movie_posters`
WITH CONNECTION `us.gemini_conn`
OPTIONS (
  object_metadata = 'SIMPLE',
  uris = ['gs://cloud-samples-data/vertex-ai/dataset-management/datasets/classic-movie-posters/*']
  );

Query is running:   0%|          |

Empty DataFrame
Columns: []
Index: []

In [59]:
%%bigquery
SELECT * FROM `gemini_demo.movie_posters` LIMIT 5

Query is running:   0%|          |

Downloading:   0%|          |

,uri,generation,content_type,size,md5_hash,updated,metadata,ref
0,gs://cloud-samples-data/vertex-ai/dataset-mana...,1683653079811418,image/jpeg,81952,8b48292aba74c3c1812ca7bdd0be7fa7,2023-05-09 17:24:39.856000+00:00,[],{'uri': 'gs://cloud-samples-data/vertex-ai/dat...
1,gs://cloud-samples-data/vertex-ai/dataset-mana...,1683653080024577,image/jpeg,30086,1a831e349e8f954abc9fabe120fb9220,2023-05-09 17:24:40.069000+00:00,[],{'uri': 'gs://cloud-samples-data/vertex-ai/dat...
2,gs://cloud-samples-data/vertex-ai/dataset-mana...,1683653080233711,image/jpeg,147585,c18dd6e6a87d75a95801c47f97545706,2023-05-09 17:24:40.280000+00:00,[],{'uri': 'gs://cloud-samples-data/vertex-ai/dat...
3,gs://cloud-samples-data/vertex-ai/dataset-mana...,1683653080449371,image/jpeg,107821,93d93b6aacb9b1d8ace3c037d683a961,2023-05-09 17:24:40.495000+00:00,[],{'uri': 'gs://cloud-samples-data/vertex-ai/dat...
4,gs://cloud-samples-data/vertex-ai/dataset-mana...,1683653080624441,image/jpeg,96294,c78573f7f29b9da284b1a2dda85654e9,2023-05-09 17:24:40.669000+00:00,[],{'uri': 'gs://cloud-samples-data/vertex-ai/dat...

# Perform analysis on the movie poster images

## Prompt Gemini to analyze the movie poster image object table

In [66]:
%%bigquery
CREATE OR REPLACE TABLE
  `gemini_demo.movie_posters_results` AS (
  SELECT
    uri,
    STRING(OBJ.GET_ACCESS_URL(ref,'r').access_urls.read_url) AS signed_url,
    AI.GENERATE(
      prompt => ('What is the movie title and year of release for this poster?', OBJ.GET_ACCESS_URL(ref, 'r')),
      output_schema => 'title STRING, year INT64'
    ).* EXCEPT(full_response,status)
  FROM
    `gemini_demo.movie_posters`
);

Query is running:   0%|          |

Empty DataFrame
Columns: []
Index: []

In [67]:
%%bigquery
SELECT * FROM `gemini_demo.movie_posters_results`

Query is running:   0%|          |

Downloading:   0%|          |

,uri,signed_url,title,year
0,gs://cloud-samples-data/vertex-ai/dataset-mana...,https://storage.googleapis.com/cloud-samples-d...,Barque sortant du port,1895
1,gs://cloud-samples-data/vertex-ai/dataset-mana...,https://storage.googleapis.com/cloud-samples-d...,The Great Train Robbery,1903
2,gs://cloud-samples-data/vertex-ai/dataset-mana...,https://storage.googleapis.com/cloud-samples-d...,Mabel's Busy Day,1914
3,gs://cloud-samples-data/vertex-ai/dataset-mana...,https://storage.googleapis.com/cloud-samples-d...,Les Vampires,1915
4,gs://cloud-samples-data/vertex-ai/dataset-mana...,https://storage.googleapis.com/cloud-samples-d...,He Did and He Didn't,1916
5,gs://cloud-samples-data/vertex-ai/dataset-mana...,https://storage.googleapis.com/cloud-samples-d...,Shoulder Arms,1918
6,gs://cloud-samples-data/vertex-ai/dataset-mana...,https://storage.googleapis.com/cloud-samples-d...,Little Lord Fauntleroy,1921
7,gs://cloud-samples-data/vertex-ai/dataset-mana...,https://storage.googleapis.com/cloud-samples-d...,Felix in Hollywood,1923
8,gs://cloud-samples-data/vertex-ai/dataset-mana...,https://storage.googleapis.com/cloud-samples-d...,AU SECOURS!,1924
9,gs://cloud-samples-data/vertex-ai/dataset-mana...,https://storage.googleapis.com/cloud-samples-d...,West of Hot Dog,1924
10,gs://cloud-samples-data/vertex-ai/dataset-mana...,https://storage.googleapis.com/cloud-samples-d...,Little Annie Rooney,1925
11,gs://cloud-samples-data/vertex-ai/dataset-mana...,https://storage.googleapis.com/cloud-samples-d...,Sally of the Sawdust,1925
12,gs://cloud-samples-data/vertex-ai/dataset-mana...,https://storage.googleapis.com/cloud-samples-d...,The Lost World,1925
13,gs://cloud-samples-data/vertex-ai/dataset-mana...,https://storage.googleapis.com/cloud-samples-d...,The Merry Widow,1925
14,gs://cloud-samples-data/vertex-ai/dataset-mana...,https://storage.googleapis.com/cloud-samples-d...,Der Student von Prag,1926
15,gs://cloud-samples-data/vertex-ai/dataset-mana...,https://storage.googleapis.com/cloud-samples-d...,Brown of Harvard,1926
16,gs://cloud-samples-data/vertex-ai/dataset-mana...,https://storage.googleapis.com/cloud-samples-d...,Battling Butler,1926
17,gs://cloud-samples-data/vertex-ai/dataset-mana...,https://storage.googleapis.com/cloud-samples-d...,The Beloved Rogue,1927
18,gs://cloud-samples-data/vertex-ai/dataset-mana...,https://storage.googleapis.com/cloud-samples-d...,Putting Pants on Philip,1927

## Prompt Gemini to provide movie summaries for each movie poster image

In [69]:
%%bigquery
SELECT
  uri,
  title,
  year,
  AI.GENERATE(
    prompt => ('Provide a short summary of movie titled ' || title || ' from the year ' || year)
    ).result AS movie_summary
FROM
  `gemini_demo.movie_posters_results`

Query is running:   0%|          |

Downloading:   0%|          |

,uri,title,year,movie_summary
0,gs://cloud-samples-data/vertex-ai/dataset-mana...,Mabel's Busy Day,1914,**Mabel's Busy Day (1914)** stars Mabel Norman...
1,gs://cloud-samples-data/vertex-ai/dataset-mana...,The Lost World,1925,"""The Lost World"" (1925) is a pioneering silent..."
2,gs://cloud-samples-data/vertex-ai/dataset-mana...,He Did and He Didn't,1916,**He Did and He Didn't** is a 1916 American si...
3,gs://cloud-samples-data/vertex-ai/dataset-mana...,The Merry Widow,1925,"Erich von Stroheim's lavish 1925 silent film, ..."
4,gs://cloud-samples-data/vertex-ai/dataset-mana...,West of Hot Dog,1924,"""West of Hot Dog"" is a 1924 silent Western com..."
5,gs://cloud-samples-data/vertex-ai/dataset-mana...,Shoulder Arms,1918,Charlie Chaplin stars as his iconic Little Tra...
6,gs://cloud-samples-data/vertex-ai/dataset-mana...,Sally of the Sawdust,1925,"""Sally of the Sawdust"" (1925), directed by D.W..."
7,gs://cloud-samples-data/vertex-ai/dataset-mana...,The Beloved Rogue,1927,"""The Beloved Rogue"" (1927) stars John Barrymor..."
8,gs://cloud-samples-data/vertex-ai/dataset-mana...,The Great Train Robbery,1903,*The Great Train Robbery* (1903) is a silent W...
9,gs://cloud-samples-data/vertex-ai/dataset-mana...,Little Lord Fauntleroy,1921,The 1921 film **Little Lord Fauntleroy** stars...
10,gs://cloud-samples-data/vertex-ai/dataset-mana...,AU SECOURS!,1924,*Au Secours!* (Help!) is a 1924 French silent ...
11,gs://cloud-samples-data/vertex-ai/dataset-mana...,Der Student von Prag,1926,The 1926 German silent film *Der Student von P...
12,gs://cloud-samples-data/vertex-ai/dataset-mana...,Barque sortant du port,1895,"""Barque sortant du port"" (Boat Leaving the Por..."
13,gs://cloud-samples-data/vertex-ai/dataset-mana...,Les Vampires,1915,*Les Vampires* (1915) is a seminal French sile...
14,gs://cloud-samples-data/vertex-ai/dataset-mana...,Felix in Hollywood,1923,"In ""Felix in Hollywood"" (1923), Felix the Cat,..."
15,gs://cloud-samples-data/vertex-ai/dataset-mana...,Little Annie Rooney,1925,"""Little Annie Rooney"" (1925) stars Mary Pickfo..."
16,gs://cloud-samples-data/vertex-ai/dataset-mana...,Brown of Harvard,1926,The 1926 silent film *Brown of Harvard* tells ...
17,gs://cloud-samples-data/vertex-ai/dataset-mana...,Battling Butler,1926,"""Battling Butler"" (1926) is a silent comedy st..."
18,gs://cloud-samples-data/vertex-ai/dataset-mana...,Putting Pants on Philip,1927,"""Putting Pants on Philip"" (1927) is a Laurel a..."

# Join analysis results with structured data for deeper insights
Using text embeddings to perform similarity joins of movie poster images to a movie reviews dataset in BigQuery

## Generate text embeddings for title and year associated with movie posters

In [74]:
%%bigquery
CREATE OR REPLACE TABLE
  `gemini_demo.movie_posters_results_embeddings` AS (
  SELECT
    title,
    year,
    uri,
    AI.EMBED(
      content => 'The movie titled ' || title || ' from the year ' || year,
      endpoint => 'gemini-embedding-001'
    ).result AS embedding
  FROM
    `gemini_demo.movie_posters_results`
);

Query is running:   0%|          |

Empty DataFrame
Columns: []
Index: []

In [72]:
%%bigquery
SELECT * FROM `gemini_demo.movie_posters_results_embeddings` LIMIT 5

Query is running:   0%|          |

Downloading:   0%|          |

,title,year,uri,embedding
0,Barque sortant du port,1895,gs://cloud-samples-data/vertex-ai/dataset-mana...,"[-0.012666374444961548, 0.02926185168325901, -..."
1,The Great Train Robbery,1903,gs://cloud-samples-data/vertex-ai/dataset-mana...,"[-0.012740416452288628, 0.0588647685945034, 0...."
2,Mabel's Busy Day,1914,gs://cloud-samples-data/vertex-ai/dataset-mana...,"[-0.02016374096274376, 0.039157968014478683, -..."
3,Les Vampires,1915,gs://cloud-samples-data/vertex-ai/dataset-mana...,"[-0.03295908495783806, -0.006152865011245012, ..."
4,He Did and He Didn't,1916,gs://cloud-samples-data/vertex-ai/dataset-mana...,"[0.012607629410922527, -0.02199331670999527, 0..."

## Generate text embeddings for subset of IMDB dataset

In [35]:
%%bigquery
# Create table containing movie_id, title, and year for movies in IMDB reviews dataset that were release prior to 1935
CREATE OR REPLACE VIEW
  `gemini_demo.imdb_movies` AS (
  WITH
    reviews AS (
      SELECT
        reviews.movie_id AS movie_id,
        title.primary_title AS title,
        title.start_year AS year,
        reviews.review AS review
      FROM
        `bigquery-public-data.imdb.reviews` reviews
      LEFT JOIN
        `bigquery-public-data.imdb.title_basics` title
      ON
        reviews.movie_id = title.tconst)
  SELECT
    DISTINCT(movie_id),
    title,
    year
  FROM
    reviews
  WHERE
    year < 1935)

Query is running:   0%|          |

Empty DataFrame
Columns: []
Index: []

In [75]:
%%bigquery
CREATE OR REPLACE TABLE
  `gemini_demo.imdb_movies_embeddings` AS (
  SELECT
    title,
    year,
    movie_id,
    AI.EMBED(
      content => 'The movie titled ' || title || ' from the year ' || year,
      endpoint => 'gemini-embedding-001'
    ).result AS embedding
  FROM
    `gemini_demo.imdb_movies`
);

Query is running:   0%|          |

Empty DataFrame
Columns: []
Index: []

In [73]:
%%bigquery
SELECT * FROM `gemini_demo.imdb_movies_embeddings` LIMIT 5

Query is running:   0%|          |

Downloading:   0%|          |

,title,year,movie_id,embedding
0,Dickson Experimental Sound Film,1894,tt0177707,"[0.021869907155632973, 0.02849498577415943, -0..."
1,Rough Sea at Dover,1895,tt0000030,"[0.027348332107067108, 0.032969847321510315, -..."
2,Leaving the Factory,1895,tt0000010,"[-0.01640487276017666, 0.03368816897273064, -0..."
3,Baby's Meal,1895,tt0000029,"[0.038399845361709595, 0.006128233857452869, 0..."
4,Boat Leaving the Port,1895,tt0000016,"[-0.012419872917234898, 0.025898495689034462, ..."

## Match movie poster images to IMDB `movie_id` using BigQuery `VECTOR_SEARCH`

In [76]:
%%bigquery
SELECT
  query.uri AS poster_uri,
  query.title AS poster_title,
  query.year AS poster_year,
  base.title AS imdb_title,
  base.year AS imdb_year,
  base.movie_id AS imdb_movie_id,
  distance
FROM
  VECTOR_SEARCH( TABLE `gemini_demo.imdb_movies_embeddings`,
    'embedding',
    TABLE `gemini_demo.movie_posters_results_embeddings`,
    'embedding',
    top_k => 1,
    distance_type => 'COSINE');

Query is running:   0%|          |

Downloading:   0%|          |

,poster_uri,poster_title,poster_year,imdb_title,imdb_year,imdb_movie_id,distance
0,gs://cloud-samples-data/vertex-ai/dataset-mana...,Battling Butler,1926,Battling Butler,1926,tt0016630,0.000000
1,gs://cloud-samples-data/vertex-ai/dataset-mana...,Little Lord Fauntleroy,1921,Little Lord Fauntleroy,1921,tt0012397,0.000000
2,gs://cloud-samples-data/vertex-ai/dataset-mana...,Putting Pants on Philip,1927,Putting Pants on Philip,1927,tt0018294,0.000000
3,gs://cloud-samples-data/vertex-ai/dataset-mana...,Mabel's Busy Day,1914,Mabel's Busy Day,1914,tt0004280,0.000000
4,gs://cloud-samples-data/vertex-ai/dataset-mana...,The Great Train Robbery,1903,The Great Train Robbery,1903,tt0000439,0.000000
5,gs://cloud-samples-data/vertex-ai/dataset-mana...,He Did and He Didn't,1916,He Did and He Didn't,1916,tt0006764,0.000000
6,gs://cloud-samples-data/vertex-ai/dataset-mana...,The Lost World,1925,The Lost World,1925,tt0016039,0.000000
7,gs://cloud-samples-data/vertex-ai/dataset-mana...,Les Vampires,1915,Les Vampires,1915,tt0006206,0.000000
8,gs://cloud-samples-data/vertex-ai/dataset-mana...,Felix in Hollywood,1923,Felix in Hollywood,1923,tt0017871,0.000000
9,gs://cloud-samples-data/vertex-ai/dataset-mana...,The Beloved Rogue,1927,The Beloved Rogue,1927,tt0017667,0.000000
10,gs://cloud-samples-data/vertex-ai/dataset-mana...,AU SECOURS!,1924,Help!,1924,tt0013845,0.185089
11,gs://cloud-samples-data/vertex-ai/dataset-mana...,Shoulder Arms,1918,Shoulder Arms,1918,tt0009611,0.000000
12,gs://cloud-samples-data/vertex-ai/dataset-mana...,The Merry Widow,1925,The Merry Widow,1925,tt0016104,0.000000
13,gs://cloud-samples-data/vertex-ai/dataset-mana...,West of Hot Dog,1924,West of Hot Dog,1924,tt0015477,0.000000
14,gs://cloud-samples-data/vertex-ai/dataset-mana...,Barque sortant du port,1895,Boat Leaving the Port,1895,tt0000016,0.094698
15,gs://cloud-samples-data/vertex-ai/dataset-mana...,Little Annie Rooney,1925,Little Annie Rooney,1925,tt0016028,0.000000
16,gs://cloud-samples-data/vertex-ai/dataset-mana...,Brown of Harvard,1926,Brown of Harvard,1926,tt0016690,0.000000
17,gs://cloud-samples-data/vertex-ai/dataset-mana...,Der Student von Prag,1926,The Student of Prague,1913,tt0003419,0.153324
18,gs://cloud-samples-data/vertex-ai/dataset-mana...,Sally of the Sawdust,1925,Sally of the Sawdust,1925,tt0016308,0.000000

Now let's join some additional information on ratings...

In [55]:
%%bigquery
SELECT
  query.uri AS poster_uri,
  query.title AS poster_title,
  query.year AS poster_year,
  base.title AS imdb_title,
  base.year AS imdb_year,
  base.movie_id AS imdb_movie_id,
  distance,
  imdb.average_rating,
  imdb.num_votes
FROM
  VECTOR_SEARCH( TABLE `gemini_demo.imdb_movies_embeddings`,
    'embedding',
    TABLE `gemini_demo.movie_posters_results_embeddings`,
    'embedding',
    top_k => 1,
    distance_type => 'COSINE') DATA
LEFT JOIN
  `bigquery-public-data.imdb.title_ratings` imdb
ON
  base.movie_id = imdb.tconst
ORDER BY
  imdb.average_rating DESC

Query is running:   0%|          |

Downloading:   0%|          |

,poster_uri,poster_title,poster_year,imdb_title,imdb_year,imdb_movie_id,distance,average_rating,num_votes
0,gs://cloud-samples-data/vertex-ai/dataset-mana...,Les Vampires,1915,Les Vampires,1915,tt0006206,0.000000,7.3,5857
1,gs://cloud-samples-data/vertex-ai/dataset-mana...,Shoulder Arms,1918,Shoulder Arms,1918,tt0009611,0.000000,7.3,7965
2,gs://cloud-samples-data/vertex-ai/dataset-mana...,The Merry Widow,1925,The Merry Widow,1925,tt0016104,0.000000,7.2,2729
3,gs://cloud-samples-data/vertex-ai/dataset-mana...,The Great Train Robbery,1903,The Great Train Robbery,1903,tt0000439,0.000000,7.2,22637
4,gs://cloud-samples-data/vertex-ai/dataset-mana...,Battling Butler,1926,Battling Butler,1926,tt0016630,0.000000,7.0,4373
5,gs://cloud-samples-data/vertex-ai/dataset-mana...,The Beloved Rogue,1927,The Beloved Rogue,1927,tt0017667,0.000000,7.0,980
6,gs://cloud-samples-data/vertex-ai/dataset-mana...,The Lost World,1925,The Lost World,1925,tt0016039,0.000000,7.0,6527
7,gs://cloud-samples-data/vertex-ai/dataset-mana...,Little Annie Rooney,1925,Little Annie Rooney,1925,tt0016028,0.000000,6.8,1121
8,gs://cloud-samples-data/vertex-ai/dataset-mana...,Little Lord Fauntleroy,1921,Little Lord Fauntleroy,1921,tt0012397,0.000000,6.7,396
9,gs://cloud-samples-data/vertex-ai/dataset-mana...,Sally of the Sawdust,1925,Sally of the Sawdust,1925,tt0016308,0.000000,6.6,633
10,gs://cloud-samples-data/vertex-ai/dataset-mana...,Felix in Hollywood,1923,Felix in Hollywood,1923,tt0017871,0.000000,6.5,1093
11,gs://cloud-samples-data/vertex-ai/dataset-mana...,Putting Pants on Philip,1927,Putting Pants on Philip,1927,tt0018294,0.000000,6.5,1176
12,gs://cloud-samples-data/vertex-ai/dataset-mana...,He Did and He Didn't,1916,He Did and He Didn't,1916,tt0006764,0.000000,6.4,360
13,gs://cloud-samples-data/vertex-ai/dataset-mana...,Der Student von Prag,1926,The Student of Prague,1913,tt0003419,0.134451,6.4,2679
14,gs://cloud-samples-data/vertex-ai/dataset-mana...,Brown of Harvard,1926,Brown of Harvard,1926,tt0016690,0.000000,6.2,1573
15,gs://cloud-samples-data/vertex-ai/dataset-mana...,AU SECOURS!,1924,The Movies,1925,tt0016129,0.198073,6.0,162
16,gs://cloud-samples-data/vertex-ai/dataset-mana...,Barque sortant du port,1895,Boat Leaving the Port,1895,tt0000016,0.071325,5.9,1707
17,gs://cloud-samples-data/vertex-ai/dataset-mana...,West of Hot Dog,1924,West of Hot Dog,1924,tt0015477,0.000000,5.5,335
18,gs://cloud-samples-data/vertex-ai/dataset-mana...,Mabel's Busy Day,1914,Mabel's Busy Day,1914,tt0004280,0.000000,5.4,1141

# Cleaning up

To clean up all Google Cloud resources used in this project, you can [delete the Google Cloud project](https://cloud.google.com/resource-manager/docs/creating-managing-projects#shutting_down_projects) you used for the tutorial.

Otherwise, you can delete the individual resources you created in this tutorial by uncommenting the below:

In [ ]:
#
# !bq rm -r -f $PROJECT_ID:gemini_demo
#

# Wrap up

In this you have seen an example of how to integrate BigQuery with Vertex AI LLMs, and given examples of how the `AI.GENERATE` function can be applied directly to multimodal data stored in BigQuery, as well as how to generate embeddings with `AI.EMbED`.

Check out our BigQuery documentation on [generating text](https://docs.cloud.google.com/bigquery/docs/reference/standard-sql/bigqueryml-syntax-ai-generate) and [generating embeddings](https://docs.cloud.google.com/bigquery/docs/reference/standard-sql/bigqueryml-syntax-ai-embed) to learn more about generative AI in BigQuery.